/**
 * ReportActionsBar - Reusable action bar for report screens
 * Provides Print (58mm/80mm) and Email PDF functionality
 */

import React, { useState } from 'react';
import { View, StyleSheet, Alert } from 'react-native';
import { Button, useTheme } from 'react-native-paper';
import * as Print from 'expo-print';
import * as MailComposer from 'expo-mail-composer';
import * as FileSystem from 'expo-file-system/legacy';
import PrintOptionsDialog from './PrintOptionsDialog';
import { ESCPOSBuilder } from '../utils/escpos';

interface ReportActionsBarProps {
  onBuildPrintData: (printerWidth: number) => ESCPOSBuilder;
  onBuildPdfHtml: () => string;
  reportTitle: string;
  reportFileName: string;
  emailBody?: string;
  disabled?: boolean;
  compact?: boolean;
}

export default function ReportActionsBar({
  onBuildPrintData,
  onBuildPdfHtml,
  reportTitle,
  reportFileName,
  emailBody,
  disabled = false,
  compact = false,
}: ReportActionsBarProps) {
  const theme = useTheme();
  const [printDialogVisible, setPrintDialogVisible] = useState(false);
  const [exporting, setExporting] = useState(false);

  const handleEmail = async () => {
    try {
      setExporting(true);

      const isAvailable = await MailComposer.isAvailableAsync();
      if (!isAvailable) {
        Alert.alert('Error', 'Email is not available on this device.');
        return;
      }

      const html = onBuildPdfHtml();

      const { uri } = await Print.printToFileAsync({
        html,
        base64: false,
      });

      // Copy to a proper location with .pdf extension
      const fileName = `${reportFileName.replace(/[^a-zA-Z0-9_.-]/g, '_')}.pdf`;
      const newUri = `${FileSystem.cacheDirectory}${fileName}`;
      await FileSystem.copyAsync({ from: uri, to: newUri });

      const defaultBody = emailBody || `Please find attached the ${reportTitle}.\n\nGenerated by IgoroTech POS`;

      await MailComposer.composeAsync({
        recipients: [],
        subject: reportTitle,
        body: defaultBody,
        attachments: [newUri],
      });
    } catch (error) {
      console.error('Email error:', error);
      Alert.alert('Email Error', 'Failed to send email');
    } finally {
      setExporting(false);
    }
  };

  return (
    <>
      <View style={[styles.container, compact && styles.containerCompact]}>
        <Button
          mode="contained"
          icon="printer"
          onPress={() => setPrintDialogVisible(true)}
          disabled={disabled || exporting}
          style={[styles.button, { backgroundColor: theme.colors.primary }]}
          compact={compact}
          labelStyle={[styles.buttonLabel, compact && styles.labelCompact]}
          textColor="#FFFFFF"
        >
          Print
        </Button>

        <Button
          mode="contained"
          icon="email-outline"
          onPress={handleEmail}
          loading={exporting}
          disabled={disabled || exporting}
          style={[styles.button, styles.emailButton]}
          compact={compact}
          labelStyle={[styles.buttonLabel, compact && styles.labelCompact]}
          textColor="#FFFFFF"
        >
          Email
        </Button>
      </View>

      {printDialogVisible && (
        <PrintOptionsDialog
          visible={printDialogVisible}
          onDismiss={() => setPrintDialogVisible(false)}
          title={`Print ${reportTitle}`}
          onPrint={onBuildPrintData}
          onBuildPdfHtml={onBuildPdfHtml}
        />
      )}
    </>
  );
}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    gap: 8,
    padding: 8,
  },
  containerCompact: {
    padding: 4,
    gap: 4,
  },
  button: {
    flex: 1,
  },
  emailButton: {
    backgroundColor: '#2196F3',
  },
  buttonLabel: {
    color: '#FFFFFF',
  },
  labelCompact: {
    fontSize: 12,
  },
});
